MODEL:
  PRETRAIN_CHOICE: 'imagenet'
  PRETRAIN_PATH_T: '/15127306268/wyh/UIS/pth/vitb_16_224_21k.pth'
  TRANSFORMER_TYPE: 'vit_base_patch16_224'
  STRIDE_SIZE: [ 16, 16 ]
  SIE_CAMERA: True
  RE: 1
  RE_LAYER: 1
  DIRECT: 0 # We find that for vehicle reid, indirect is better than direct
INPUT:
  SIZE_TRAIN: [ 256, 128 ] # For VehicleID, you can also use [128,256], we simply use the same setting as Person-ReID
  SIZE_TEST: [ 256, 128 ]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
DATALOADER:
  SAMPLER: 'softmax_triplet'

DATASETS:
  NAMES: ('MSVR310')
  ROOT_DIR: '/15127306268/wyh/MM/data/'

SOLVER:
  MAX_EPOCHS: 1000
  BASE_LR: 0.001
  WARMUP_ITERS: 100

TEST:
  RE_RANKING: 'no'
  WEIGHT: ''
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'
  MISS: 'None'

OUTPUT_DIR: './MSVR310/TOP-ReID'

